services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/taskflow
      SPRING_DATASOURCE_USERNAME: taskflow_user
      SPRING_DATASOURCE_PASSWORD: taskflow_password
      APP_JWT_SECRET: my_super_secret_key_that_is_at_least_32_characters_long
      APP_CORS_ALLOWED_ORIGINS: "http://localhost:5174,http://localhost:5173"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: taskflow
      MYSQL_USER: taskflow_user
      MYSQL_PASSWORD: taskflow_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3310:3306"  
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
